name: 自动部署到云服务器

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v3

      - name: 设置 SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: 部署到云服务器
        run: |
          ssh -o StrictHostKeyChecking=no root@118.31.33.58 << 'EOF'
            cd /var/www/训练1
            git pull
            systemctl restart uwsgi
            systemctl restart nginx
          EOF
